// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contactanos: dynamic(() => import("./Contactanos")),
  header: dynamic(() => import("./Header")),
  nosotros: dynamic(() => import("./Nosotros")),
  nuestros_desarrollos: dynamic(() => import("./NuestrosDesarrollos")),
};
